[terminals]
exact = [
    "kitty",
    "kovidgoyal-kitty",
    "Alacritty",
    "alacritty",
    "org.wezfurlong.wezterm",
    "wezterm",
    "konsole",
    "Konsole",
    "gnome-terminal",
    "Gnome-terminal",
    "xterm",
    "XTerm",
    "urxvt",
    "URxvt",
    "st",
    "st-256color",
    "foot",
    "footclient",
    "com.mitchellh.ghostty",
    "ghostty",
    "terminal",
    "Termulator",
    "terminator",
    "Terminator",
    "tilix",
    "Tilix",
    "guake",
    "Guake",
    "tilda",
    "Tilda",
    "yakuake",
    "sakura",
    "roxterm",
    "lxterminal",
    "Lxterminal",
    "mate-terminal",
    "xfce4-terminal",
    "qterminal",
    "hyper",
    "terminology",
]
substrings = [
    "terminal",
    "konsole",
    "xterm",
    "alacritty",
    "wezterm",
    "ghostty",
    "kitty",
]
